version: '3.8'

services:
  django-forum:
    build:
      context: .
    container_name: roumerchi_core_api
    ports:
      - "8001:8001"
    command: > #python manage.py runserver 0.0.0.0:8001 | gunicorn --bind=0.0.0.0:8000 --log-level=debug avalance.wsgi:application
      sh -c "python manage.py runserver 0.0.0.0:8001 "
    healthcheck:
      test: curl -f http://localhost/roumerchi/api/healthcheck || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: on-failure:5
    volumes:
      - static_volume:/avalance/tests/static
    networks:
      - internet
      - localnet

  nginx:
    image: nginx
    container_name: roumerchi_nginx
    depends_on:
      - django-forum
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
      - ./../nginx_static/codes:/primal_static/errors/codes
      - ./../nginx_static/css:/primal_static/errors/css
      - ./../nginx_static/icons:/primal_static/icons
      - ./robots.txt:/primal_static/robots.txt
      - ./browserconfig.xml:/primal_static/browserconfig.xml
      - ./manifest.json:/primal_static/manifest.json
    command: >
      /bin/sh -c "
      if [ ! -f /etc/nginx/ssl/nginx.key ]; then
        mkdir -p /etc/nginx/ssl && openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt -subj '/CN=localhost';
      fi &&
      nginx -g 'daemon off;'"
    networks:
      - internet

volumes:
  static_volume:

networks:
  internet:
    name: internet
    driver: bridge
  localnet:
    name: localnet
    driver: bridge
